services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}  # Use the actual environment variable
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}  # Use the actual environment variable
      SESSION_SECRET: cat
    volumes:
      - .:/app
    command: npm start
    depends_on:
      - redis
  redis:
    image: "redis:alpine"